const express = require('express');
const router = express.Router();
const adminController = require('../controllers/adminController');
const adminStatsController = require('../controllers/adminStatsController');
const adminMarketController = require('../controllers/adminMarketController');
const adminJdBenefitController = require('../controllers/adminJdBenefitController');
const adminRefundController = require('../controllers/adminRefundController');
const adminSettlementController = require('../controllers/adminSettlementController');
const adminMerchantAccountController = require('../controllers/adminMerchantAccountController');
const adminRiskController = require('../controllers/adminRiskController');
const adminOpsController = require('../controllers/adminOpsController');
const adminHousekeepingController = require('../controllers/adminHousekeepingController');
const adminDispatchController = require('../controllers/adminDispatchController');
const adminAuthMiddleware = require('../middlewares/adminAuthMiddleware');

router.use(adminAuthMiddleware);

router.get('/stats/overview', adminStatsController.overview);
router.get('/worker-applications', adminController.getWorkerApplications);
router.put('/worker-applications/:id', adminController.updateWorkerApplication);
router.get('/service-provider-applications', adminMarketController.listServiceProviderApplications);
router.put('/service-provider-applications/:id', adminMarketController.updateServiceProviderApplication);
router.get('/live-streams', adminController.listLiveStreams);
router.post('/live-streams', adminController.createLiveStream);
router.put('/live-streams/:id', adminController.updateLiveStream);
router.delete('/live-streams/:id', adminController.deleteLiveStream);

router.get('/housekeeping/orders', adminHousekeepingController.listOrders);
router.get('/housekeeping/workers', adminHousekeepingController.listWorkers);
router.post('/housekeeping/orders/:id/dispatch', adminHousekeepingController.dispatchOrder);

router.get('/dispatch-queue', adminDispatchController.dispatchQueue);
router.get('/service-orders', adminDispatchController.listServiceOrders);
router.post('/service-orders/:id/assign', adminDispatchController.assignServiceOrder);
router.get('/neighbor-assist/orders', adminDispatchController.listNeighborAssistOrders);
router.post('/neighbor-assist/orders/:id/assign', adminDispatchController.assignNeighborAssistOrder);

router.get('/market-orders', adminMarketController.listOrders);
router.get('/market-orders/:orderNo', adminMarketController.getOrderDetail);
router.get('/order-fulfillment', adminMarketController.listOrderFulfillment);
router.post('/market-orders/:orderNo/actions', adminMarketController.applyOrderAction);
router.get('/market-payments', adminMarketController.listPayments);
router.get('/refunds', adminRefundController.list);
router.get('/refunds/export/csv', adminRefundController.exportCsv);
router.get('/refunds/:id', adminRefundController.detail);
router.post('/refunds/apply', adminRefundController.apply);
router.post('/refunds/:id/review', adminRefundController.review);
router.post('/refunds/:id/execute', adminRefundController.execute);
router.get('/reconcile/summary', adminSettlementController.reconcileSummary);
router.get('/settlements', adminSettlementController.listSettlementBills);
router.post('/settlements/generate', adminSettlementController.generateSettlement);
router.get('/settlements/export/csv', adminSettlementController.exportSettlementCsv);
router.get('/market-shops', adminMarketController.listShops);
router.post('/market-shops', adminMarketController.createShop);
router.get('/market-shops/:id', adminMarketController.getShop);
router.put('/market-shops/:id', adminMarketController.updateShop);
router.get('/market-goods', adminMarketController.listGoods);
router.post('/market-goods', adminMarketController.createGood);
router.put('/market-goods/:id', adminMarketController.updateGood);
router.post('/market-goods/batch-update', adminMarketController.batchUpdateGoods);
router.get('/market-goods/low-stock', adminMarketController.lowStockGoods);
router.get('/market-applications', adminMarketController.listMarketApplications);
router.put('/market-applications/:id', adminMarketController.updateMarketApplication);
router.get('/market-shop-reviews', adminMarketController.listReviews);
router.delete('/market-shop-reviews/:id', adminMarketController.deleteReview);
router.get('/merchant-accounts', adminMerchantAccountController.list);
router.post('/merchant-accounts', adminMerchantAccountController.create);
router.put('/merchant-accounts/:id', adminMerchantAccountController.update);
router.post('/merchant-accounts/:id/reset-password', adminMerchantAccountController.resetPassword);
router.get('/complaint-tickets', adminRiskController.listComplaints);
router.post('/complaint-tickets', adminRiskController.createComplaint);
router.put('/complaint-tickets/:id', adminRiskController.resolveComplaint);
router.get('/approval-records', adminRiskController.listApprovalRecords);
router.get('/operation-logs', adminRiskController.listOperationLogs);
router.get('/coupon-templates', adminOpsController.listCouponTemplates);
router.post('/coupon-templates', adminOpsController.createCouponTemplate);
router.post('/coupon-issues/issue', adminOpsController.issueCoupon);
router.get('/coupon-issues', adminOpsController.listCouponIssues);
router.get('/activities', adminOpsController.listActivities);
router.post('/activities', adminOpsController.createActivity);
router.get('/reports', adminOpsController.dataReport);
router.get('/jd-benefit-goods', adminJdBenefitController.list);
router.post('/jd-benefit-goods', adminJdBenefitController.create);
router.put('/jd-benefit-goods/:id', adminJdBenefitController.update);
router.delete('/jd-benefit-goods/:id', adminJdBenefitController.destroy);

module.exports = router;
